name: mental_health_monitor_actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  # Workflow "lint"
  lint:
    name: "Linting"
    runs-on: ubuntu-latest
    steps:
      - name: Lint Init Msg
        run: 'echo "Linting in progress..."'

      - name: Clone the repo
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      # - name: Caching dependencies
      #   id: cache-deps
      #   uses: actions/cache@v4
      #   env:
      #     cache-name: cache-dependencies
      #   with:
      #     path: ~/cache/dependencies
      #     key: ${{ runner.os }}-build-${{ env.cache-name }}
  
      - name: Install dependencies
      # if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Run PyLint
        run: pylint --fail-under=8 "*/*.py"

  # Workflow "test"
  test:
    name: "Testing"
    runs-on: ubuntu-latest
    steps:
      - name: Test Init Msg
        run: 'echo "Testing in progress..."'

      - name: Clone the repo
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      # - name: Caching dependencies
      #   id: cache-deps
      #   uses: actions/cache@v4
      #   env:
      #     cache-name: cache-dependencies
      #   with:
      #     path: ~/cache/dependencies
      #     key: ${{ runner.os }}-build-${{ env.cache-name }}
          

      - name: Install dependencies
      # if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run PyTest
        run: pytest -k "test"
